# Generated by Django 3.0.6 on 2020-06-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20200604_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerride',
            old_name='ride_id',
            new_name='ride',
        ),
    ]
