# Generated by Django 3.0.6 on 2020-06-05 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20200604_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='phone',
            field=models.CharField(default='0884124584', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='startPoint',
            field=models.CharField(default='Pleven', max_length=15),
            preserve_default=False,
        ),
    ]
